name: Tmate Debug Session

on:
  workflow_dispatch:  # bisa dijalankan manual lewat UI GitHub

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start tmate SSH session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true  # hanya kamu yang bisa akses session
