name: Test tmate Connection

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Keep session alive for 15 minutes
        run: sleep 900
