name: WebSSH Debug

on:
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start WebSSH
        uses: P3TERX/ssh2actions@main
        # opsional: kamu bisa tambahkan token telegram kalau mau notifikasi
